# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.


import os
import pandas as pd


# load configuration
# -----------------------------------------------------
configfile: "config/config.yml"


# container definition: uncomment to include a singularity image, e.g. from github's container registry
# container: "oras://ghcr.io/<user>/<repository>:<version>"


# load rules
# -----------------------------------------------------
include: "rules/common.smk"
include: "rules/process_reads.smk"


# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("--- Workflow finished! ---")


onerror:
    print("--- An error occurred! ---")


# target rules
# -----------------------------------------------------
rule all:
    input:
        "results/multiqc/multiqc_report.html",
    default_target: True
